/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthPlayersImport } from './routes/_auth.players'
import { Route as AuthHomeImport } from './routes/_auth.home'
import { Route as AuthConsoleImport } from './routes/_auth.console'
import { Route as AuthChatImport } from './routes/_auth.chat'
import { Route as AuthBansImport } from './routes/_auth.bans'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPlayersRoute = AuthPlayersImport.update({
  path: '/players',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHomeRoute = AuthHomeImport.update({
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)

const AuthConsoleRoute = AuthConsoleImport.update({
  path: '/console',
  getParentRoute: () => AuthRoute,
} as any)

const AuthChatRoute = AuthChatImport.update({
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBansRoute = AuthBansImport.update({
  path: '/bans',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/bans': {
      preLoaderRoute: typeof AuthBansImport
      parentRoute: typeof AuthImport
    }
    '/_auth/chat': {
      preLoaderRoute: typeof AuthChatImport
      parentRoute: typeof AuthImport
    }
    '/_auth/console': {
      preLoaderRoute: typeof AuthConsoleImport
      parentRoute: typeof AuthImport
    }
    '/_auth/home': {
      preLoaderRoute: typeof AuthHomeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/players': {
      preLoaderRoute: typeof AuthPlayersImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthBansRoute,
    AuthChatRoute,
    AuthConsoleRoute,
    AuthHomeRoute,
    AuthPlayersRoute,
  ]),
])

/* prettier-ignore-end */
